
def generate_report(zone, risk_level, plan):

    report = f'''
🌍 FLOOD EMERGENCY REPORT
----------------------------

📍 Zone: {zone}
⚠️ Risk Level: {risk_level}

🚨 Alert:
{plan['alert']}

🛟 Resources Needed:
{', '.join(plan['resources'])}

✅ Action Plan:
{plan['action']}

----------------------------
Generated by FloodGuard AI
'''

    return report

if __name__ == "__main__":
    from response_agent import response_agent
    plan = response_agent("High")
    print(generate_report("Test Zone", "High", plan))

    
