
def generate_report(zone, risk_level, plan):

    report = f'''
🌍 FLOOD EMERGENCY REPORT
----------------------------

📍 Zone: {zone}
⚠️ Risk Level: {risk_level}

🚨 Alert:
{plan['alert']}

🛟 Resources Needed:
{', '.join(plan['resources'])}

✅ Action Plan:
{plan['action']}

----------------------------
Generated by FloodGuard AI
'''

    return report
